version: '2'
services:
    ror:
        build: ror/.
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - ./ror/:/ror
        ports:
            - "3000:3000"
        restart: always
        networks:
            - nginx_default
    node:
        build: node/.
        command: node server.js
        #depends_on: 
        links:
            - ror
            - redis
        volumes:
            - ./node/:/node
            - /node/node_modules
        restart: always
    http:
        build: http/.
        command: http-server . -p 80
        depends_on: 
            - ror
        ports:
            - "8001:80"
        volumes:
            - ./http/:/http
            - /http/node_modules
        restart: always
        networks:
            - nginx_default
    redis:
        image: redis
        ports:
            - "6379:6379"
        restart: always
networks:
    nginx_default:
        external: true
